"""path_filters + goal_id

Revision ID: 4b7fe9949084
Revises: db383d01e52a
Create Date: 2026-06-12 11:58:55.181240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b7fe9949084'
down_revision: Union[str, Sequence[str], None] = 'db383d01e52a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('path_filters', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'path_filters')
    # ### end Alembic commands ###
