"""modules 2-18 schema

Revision ID: db383d01e52a
Revises: 8570396e4179
Create Date: 2026-06-12 10:52:10.108166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db383d01e52a'
down_revision: Union[str, Sequence[str], None] = '8570396e4179'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fun_facts',
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text')
    )
    op.create_table('learning_hub_classes',
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('cwe', sa.String(length=32), nullable=True),
    sa.Column('owasp', sa.String(length=32), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('faq', sa.JSON(), nullable=False),
    sa.Column('resources', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_hub_classes_category'), 'learning_hub_classes', ['category'], unique=False)
    op.create_index(op.f('ix_learning_hub_classes_name'), 'learning_hub_classes', ['name'], unique=False)
    op.create_index(op.f('ix_learning_hub_classes_slug'), 'learning_hub_classes', ['slug'], unique=True)
    op.create_table('api_keys',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('encrypted_key', sa.String(length=1000), nullable=False),
    sa.Column('last_four', sa.String(length=4), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_user_provider')
    )
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('custom_vulnerabilities',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('what_it_is', sa.Text(), nullable=True),
    sa.Column('detection_patterns', sa.Text(), nullable=True),
    sa.Column('what_to_look_for', sa.Text(), nullable=True),
    sa.Column('how_to_fix', sa.Text(), nullable=True),
    sa.Column('source_urls', sa.JSON(), nullable=True),
    sa.Column('researched', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_vulnerabilities_user_id'), 'custom_vulnerabilities', ['user_id'], unique=False)
    op.create_table('false_positive_suppressions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('repo', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('subcategory', sa.String(length=120), nullable=True),
    sa.Column('file_pattern', sa.String(length=600), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('origin_finding_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_false_positive_suppressions_repo'), 'false_positive_suppressions', ['repo'], unique=False)
    op.create_index(op.f('ix_false_positive_suppressions_user_id'), 'false_positive_suppressions', ['user_id'], unique=False)
    op.create_table('github_connections',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('encrypted_token', sa.String(length=1000), nullable=False),
    sa.Column('github_username', sa.String(length=120), nullable=True),
    sa.Column('github_user_id', sa.Integer(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('scopes', sa.String(length=300), nullable=True),
    sa.Column('webhook_secret', sa.String(length=64), nullable=False),
    sa.Column('triggers', sa.JSON(), nullable=False),
    sa.Column('issue_settings', sa.JSON(), nullable=False),
    sa.Column('status_check', sa.JSON(), nullable=False),
    sa.Column('repo_access', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_connections_user_id'), 'github_connections', ['user_id'], unique=True)
    op.create_table('handoff_events',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('audit_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_handoff_events_audit_id'), 'handoff_events', ['audit_id'], unique=False)
    op.create_index(op.f('ix_handoff_events_user_id'), 'handoff_events', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link', sa.JSON(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_read'), 'notifications', ['read'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('repositories',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('identifier', sa.String(length=400), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('watched', sa.Boolean(), nullable=False),
    sa.Column('frequency', sa.String(length=12), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_scan_id', sa.String(length=36), nullable=True),
    sa.Column('last_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'identifier', name='uq_user_repo_identifier')
    )
    op.create_index(op.f('ix_repositories_identifier'), 'repositories', ['identifier'], unique=False)
    op.create_index(op.f('ix_repositories_user_id'), 'repositories', ['user_id'], unique=False)
    op.create_table('usage_logs',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=True),
    sa.Column('purpose', sa.String(length=20), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_logs_provider'), 'usage_logs', ['provider'], unique=False)
    op.create_index(op.f('ix_usage_logs_scan_id'), 'usage_logs', ['scan_id'], unique=False)
    op.create_index(op.f('ix_usage_logs_user_id'), 'usage_logs', ['user_id'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('event', sa.String(length=60), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('repo', sa.String(length=300), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('triggered_scan_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_deliveries_user_id'), 'webhook_deliveries', ['user_id'], unique=False)
    op.create_table('optimization_plans',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_plans_repository_id'), 'optimization_plans', ['repository_id'], unique=False)
    op.create_index(op.f('ix_optimization_plans_user_id'), 'optimization_plans', ['user_id'], unique=False)
    op.create_table('scans',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=True),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('repo', sa.String(length=300), nullable=True),
    sa.Column('source_url', sa.String(length=600), nullable=True),
    sa.Column('branch', sa.String(length=200), nullable=True),
    sa.Column('commit', sa.String(length=64), nullable=True),
    sa.Column('depth', sa.String(length=16), nullable=False),
    sa.Column('model_mode', sa.String(length=16), nullable=False),
    sa.Column('models', sa.JSON(), nullable=False),
    sa.Column('include_custom', sa.Boolean(), nullable=False),
    sa.Column('include_optimization', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('correlation_id', sa.String(length=36), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('files', sa.Integer(), nullable=False),
    sa.Column('segment_total', sa.Integer(), nullable=False),
    sa.Column('segments_analyzed', sa.Integer(), nullable=False),
    sa.Column('security_score', sa.Integer(), nullable=True),
    sa.Column('optimization_score', sa.Integer(), nullable=True),
    sa.Column('worst_severity', sa.String(length=16), nullable=True),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_repository_id'), 'scans', ['repository_id'], unique=False)
    op.create_index(op.f('ix_scans_status'), 'scans', ['status'], unique=False)
    op.create_index(op.f('ix_scans_user_id'), 'scans', ['user_id'], unique=False)
    op.create_table('chat_logs',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('assistant_message', sa.Text(), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('refused', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_logs_scan_id'), 'chat_logs', ['scan_id'], unique=False)
    op.create_index(op.f('ix_chat_logs_user_id'), 'chat_logs', ['user_id'], unique=False)
    op.create_table('findings',
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('public_id', sa.String(length=16), nullable=False),
    sa.Column('engine', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('subcategory', sa.String(length=120), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('file', sa.String(length=600), nullable=False),
    sa.Column('line_start', sa.Integer(), nullable=False),
    sa.Column('line_end', sa.Integer(), nullable=False),
    sa.Column('code_snippet', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('fix_summary', sa.Text(), nullable=True),
    sa.Column('fix_snippet', sa.Text(), nullable=True),
    sa.Column('cwe_id', sa.String(length=32), nullable=True),
    sa.Column('owasp_ref', sa.String(length=32), nullable=True),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('model_attribution', sa.String(length=80), nullable=True),
    sa.Column('verified_by', sa.String(length=80), nullable=True),
    sa.Column('plan_id', sa.String(length=36), nullable=True),
    sa.Column('goal_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('false_positive_reason', sa.Text(), nullable=True),
    sa.Column('handoff_status', sa.String(length=20), nullable=True),
    sa.Column('fixed_via', sa.String(length=20), nullable=True),
    sa.Column('fixed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('github_issue_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_engine'), 'findings', ['engine'], unique=False)
    op.create_index(op.f('ix_findings_public_id'), 'findings', ['public_id'], unique=False)
    op.create_index(op.f('ix_findings_scan_id'), 'findings', ['scan_id'], unique=False)
    op.create_index(op.f('ix_findings_severity'), 'findings', ['severity'], unique=False)
    op.create_index(op.f('ix_findings_status'), 'findings', ['status'], unique=False)
    op.create_table('handoff_tokens',
    sa.Column('audit_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('finding_ids', sa.JSON(), nullable=True),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['scans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_handoff_tokens_audit_id'), 'handoff_tokens', ['audit_id'], unique=False)
    op.create_index(op.f('ix_handoff_tokens_user_id'), 'handoff_tokens', ['user_id'], unique=False)
    op.create_table('optimization_goals',
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['optimization_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_goals_plan_id'), 'optimization_goals', ['plan_id'], unique=False)
    op.create_table('reports',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('format', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('file_path', sa.String(length=700), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_scan_id'), 'reports', ['scan_id'], unique=False)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    op.create_table('segments',
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.String(length=600), nullable=False),
    sa.Column('language', sa.String(length=40), nullable=True),
    sa.Column('line_start', sa.Integer(), nullable=False),
    sa.Column('line_end', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('analyzed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segments_content_hash'), 'segments', ['content_hash'], unique=False)
    op.create_index(op.f('ix_segments_scan_id'), 'segments', ['scan_id'], unique=False)
    op.create_table('share_tokens',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('scan_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_tokens_scan_id'), 'share_tokens', ['scan_id'], unique=False)
    op.create_index(op.f('ix_share_tokens_slug'), 'share_tokens', ['slug'], unique=True)
    op.create_index(op.f('ix_share_tokens_user_id'), 'share_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_share_tokens_user_id'), table_name='share_tokens')
    op.drop_index(op.f('ix_share_tokens_slug'), table_name='share_tokens')
    op.drop_index(op.f('ix_share_tokens_scan_id'), table_name='share_tokens')
    op.drop_table('share_tokens')
    op.drop_index(op.f('ix_segments_scan_id'), table_name='segments')
    op.drop_index(op.f('ix_segments_content_hash'), table_name='segments')
    op.drop_table('segments')
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_scan_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_optimization_goals_plan_id'), table_name='optimization_goals')
    op.drop_table('optimization_goals')
    op.drop_index(op.f('ix_handoff_tokens_user_id'), table_name='handoff_tokens')
    op.drop_index(op.f('ix_handoff_tokens_audit_id'), table_name='handoff_tokens')
    op.drop_table('handoff_tokens')
    op.drop_index(op.f('ix_findings_status'), table_name='findings')
    op.drop_index(op.f('ix_findings_severity'), table_name='findings')
    op.drop_index(op.f('ix_findings_scan_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_public_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_engine'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_chat_logs_user_id'), table_name='chat_logs')
    op.drop_index(op.f('ix_chat_logs_scan_id'), table_name='chat_logs')
    op.drop_table('chat_logs')
    op.drop_index(op.f('ix_scans_user_id'), table_name='scans')
    op.drop_index(op.f('ix_scans_status'), table_name='scans')
    op.drop_index(op.f('ix_scans_repository_id'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_optimization_plans_user_id'), table_name='optimization_plans')
    op.drop_index(op.f('ix_optimization_plans_repository_id'), table_name='optimization_plans')
    op.drop_table('optimization_plans')
    op.drop_index(op.f('ix_webhook_deliveries_user_id'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_usage_logs_user_id'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_scan_id'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_provider'), table_name='usage_logs')
    op.drop_table('usage_logs')
    op.drop_index(op.f('ix_repositories_user_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_identifier'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_read'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_handoff_events_user_id'), table_name='handoff_events')
    op.drop_index(op.f('ix_handoff_events_audit_id'), table_name='handoff_events')
    op.drop_table('handoff_events')
    op.drop_index(op.f('ix_github_connections_user_id'), table_name='github_connections')
    op.drop_table('github_connections')
    op.drop_index(op.f('ix_false_positive_suppressions_user_id'), table_name='false_positive_suppressions')
    op.drop_index(op.f('ix_false_positive_suppressions_repo'), table_name='false_positive_suppressions')
    op.drop_table('false_positive_suppressions')
    op.drop_index(op.f('ix_custom_vulnerabilities_user_id'), table_name='custom_vulnerabilities')
    op.drop_table('custom_vulnerabilities')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_learning_hub_classes_slug'), table_name='learning_hub_classes')
    op.drop_index(op.f('ix_learning_hub_classes_name'), table_name='learning_hub_classes')
    op.drop_index(op.f('ix_learning_hub_classes_category'), table_name='learning_hub_classes')
    op.drop_table('learning_hub_classes')
    op.drop_table('fun_facts')
    # ### end Alembic commands ###
